# Gopkg.toml example

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "acmev2"
  name = "github.com/xenolf/lego"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.9"
